overrides:
  ceph:
    conf:
      osd:
        debug mclock: 30
        debug osd: 30
        osd op queue: mclock_scheduler
        osd op queue cut off: debug_random
        osd debug verify missing on start: true
        osd debug verify cached snaps: true
        bluestore zero block detection: true
        osd mclock override recovery settings: true
        osd mclock profile: high_recovery_ops
      mon:
        mon scrub interval: 300
